---
title: "Restore your libraries to the state in the lock file "
author: "Han Olff"
format: html
date: "2024-09-02"
---

renv::restore() is a function from the renv package in R that is used to restore the state of your project's R package library to the versions specified in the renv.lock file.

This renv.lock file is created the first time with renv::init(),\
After a project is initialised, new packages that are installed are installed in a library in the local folder of your project.

This ensures that your project uses the exact same package versions and dependencies that were initially recorded, making it easier to reproduce analyses and maintain consistency across different environments or collaborators. The version of packages in the library can be update by yourself or your collaborator, but then then renv::restore() causes all to use the same versions of all libraries. Be carefull with this, only update your library when really nescessary (eg a package contains an error or missing functionality). Otherwise just stick to the version that you used when you started the project.

```{r}
rm(list = ls()) # clear your R environment
renv::restore() # restore your libraries from the lock file
```
