# Working with Quarto documents in R

Markdown is a lightweight markup language used to format plain text in a simple, human-readable way. It is a simple way to format headers, tables etc for still a simple text document, such as this text, using plain text formatting. Files have the .md extension. For example, the '#' in front of the first line of this document indicates that it is a title, and needs to be formatted like that. If you switch this window of this text to the tab "visual" you see what happens. Markdown is lightweight eg compared to html (how most internet pages are written), which allows much more formatting, and makes files practically not readable anymore with a regular text editor. 

Later, Markdown  was expanded to RMarkdown, which allows to use Markdown in the context of an R Script. Files have the .Rmd extension. This allows the alternation of regular text (such as this) with so-called code-chunks of R script. It allows you to not only write a script, but also directly in the script explain why you do things a certain way, and what the result means. 

The latest development in this regard is the development of Quarto. It uses



